name: wavecode
description: "A Flutter app that encodes and decodes audio using images"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  flutter_sound: ^9.28.0
  just_audio: ^0.10.4
  file_picker: ^10.2.0
  image: ^4.5.4
  flutter_animate: ^4.5.2
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  share_plus: ^11.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/